### ISSUE TITLE
options menu breaks meido panel

### ISSUE THREAD

**Issue by agaghasghjksahgjsashg** [shamichan/shamiscript#2]
when you click on the options menu with the kiss mark the meido panel disappears until you refresh

**Comment by shamichan** [comment]
AAAAAAAAAAAAAAAAAAAAa

**Comment by shamichan** [comment]
ive figured out why that happens i will fix this tomorrow

**Comment by shamichan** [comment]
fixed now tabun please scream very loudly if it didnt fix it onegai
